name: Node.js CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
    paths-ignore:
      - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.22.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build:compile
    - run: pnpm run build --if-present
    - run: pnpm run build:test
    - run: pnpm test
      env:
        CI: true
